version: '3.7'
services:
  mysql:
    image: postgres:12-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgres
    environment:
      - POSTGRES_DB=db

      - POSTGRES_USER=karina021022
      - POSTGRES_PASSWORD=karina0210
